### ISSUE TITLE
Make "Items per page" optional

### ISSUE THREAD

**Issue by Jona5** [Peppe/PagedTable#5]
Hi,

it would be nice if we could hide the ComboBox ("Items per page").
In some Panels we do not have enough space for more entry in our PagedTable.

thanks.

**Comment by DeepaliSakunde** [comment]
Can you please name those methods?
I can't find any method to just show next page previous page , last & first page in the controls bar.

I am using Vaadin 6.8 

Thanks,
Deepali

**Comment by LivePwndz** [comment]
These methods are available via the <code>PagedTable</code> object, not the<code> createControls</code> returned object.

<code>previousPage() </code>:- Self explanatory
<code>nextPage()</code> :- Self explanatory
<code>setCurrentPage(pageNumber) </code>:- <code>pageNumber </code>could be any integer value from <code>0 - t </code> where <code>t </code>is the total number of pages. use <code>getTotalAmountOfPages()</code> to get the value of <code>t</code>. So to view the first page, call <code>setCurrentPage(0)</code>, and to view the last page, call <code>setCurrentPage(t)</code>.
Please make the effort to go through the source code. It's pretty clear.

Hope that can help you.

**Comment by DeepaliSakunde** [comment]
Thanks.
I found it.
I have another issue now.
First time when table gets populated it shows 3 pages.
When I click on next page it goes to 2nd page and total number of pages count is changed to 4 from 3
Why so?
